### ISSUE TITLE
Not changig Membership Status

### ISSUE THREAD

**Issue by mad2kx** [strangerstudios/pmpro-payfast#14]
Hi,

I have 3 Subscription levels, one of them is Free and the other two ones are paid subscriptions. The moment a member pays via payfast it does not change the usergroup from Free/New user to Premium User. I have to change every user manually through the backend.

How can I automate this?

Best,

M

**Comment by mad2kx** [comment]
Hi Andrew,

thank you for your fast response. The code and payment is working without a problem. OK will look for future updates and will change the membership status manually.

Best,

M

**Comment by andrewlimaza** [comment]
Thank you for this Martin, it's really no problem at all. We are eager to get this release working, it is really close with some final tweaks.

This code was inherited from the PayFast website (with permission etc.) to be turned into a plugin so there are some kinks we are helping them in fixing and we are nearly there. I've already done a small Pull Request to help fix an issue where it wasn't changing membership levels while testing in sandbox mode. 

I'm not sure if you are currently using the live URL or in sandbox mode?

I believe there is one more issue we need to sort out now with this version and then we should be good for more thorough testing. I'm sorry on the delay on this, we try to get things as stable as possible before releasing it publicly.

FWIW here is the Pull Request -> https://github.com/strangerstudios/pmpro-payfast/pull/15

**Comment by andrewlimaza** [comment]
Hey Martin, 

I hope you are well, it looks like we've managed to solve a couple of those issues. Please feel free to retest this on your staging site and let me know of any other issues you may come across.

Please note that if you are testing this on sandbox mode, you have the ability to run a subscription charge. If you run this subscription charge within 2 days of the initial order, it may not create a new order as the PayFast gateway only supports Monthly / Yearly within the PayFast PMPro Integration.

I hope this helps and look forward to hearing from you.

**Comment by mad2kx** [comment]
Hi Andrew,

So basically I can download the latest version from Github and upload/overwrite it on my installation?

**Comment by andrewlimaza** [comment]
Yea you could do that :)

**Comment by andrewlimaza** [comment]
It seems that this is resolved in previous updates.
