### ISSUE TITLE
Members being cancelling after Checkout

### ISSUE THREAD

**Issue by ManusHanekom** [strangerstudios/pmpro-payfast#31]
I updated PMPro to V 2.0.4. and then new members started to receive Cancelation emails instead of the Checkout- Paid Email. Admin also receives a  Cancelation [admin] email from the website. But the members are active when you check in members. Also the Cancelation email does not show a cancelation date.

I Contacted Payfast Pro with this issue, The  Current Payfast Gateway plugin only supports up to V1.9 of PMPro.

When loading a member manually we also receive a cancelation email. I have checked the php on the emails everything looks fine.

Any suggestions on a fix?

**Comment by andrewlimaza** [comment]
Hi @ManusHanekom 

Thanks for reaching out, are you using the code provided on payfast.co.za or from Paid Memberships Pro site - https://www.paidmembershipspro.com/add-ons/payfast-payment-gateway/

I am busy running some tests on this to see if I can replicate this issue.

**Comment by ManusHanekom** [comment]
Hi

Thanks. I downloaded the plugin form payfast.co.za

-----Original Message-----

**Comment by andrewlimaza** [comment]
Thanks! The version on this repository is a lot more updated.

You can remove the PayFast code that you added to PMPro core and install this plugin from your WordPress dashboard > "Memberships" > "Add Ons".

Please let me know if this helps. I am busy working through this as we speak.

**Comment by ManusHanekom** [comment]
I will work on it tonight. I have loadshedding coming in the next 30mins.

Thank you

-----Original Message-----

**Comment by ManusHanekom** [comment]
Hi

How are you? Shorted out the problem with the cancelation email by rolling
back to version 1.9.6, but know we are not receiving the checkout admin
email.

Can you assist?

**Comment by ManusHanekom** [comment]
I also recieve a update error on when i follow the payfast instructions

**Comment by ManusHanekom** [comment]
Your PHP code changes were rolled back due to an error on line 87 of file
wp-content/plugins/paid-memberships-pro/paid-memberships-pro.php. Please
fix and try saving again.

require_once(): Failed opening required
'wp-content/plugins/paid-memberships-pro/classes/gateways/class.pmprogateway_payfast.php'
(include_path='.:/usr/share/php')

**Comment by andrewlimaza** [comment]
Did you try with this plugin? We do not officially support the code Payfast provides (from their site) as that is deprecated and we will support our PayFast Add On. I have just tested this with 2.x and it works as intended.

**Comment by andrewlimaza** [comment]
Please also consider opening up a support ticket on www.paidmembershipspro.com to get official support as we don't offer in-depth support over Github.
