### ISSUE TITLE
Use HTTP API instead of CURL directly

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/pmpro-payfast#35]
Here is how we did it for PayPal Express: https://github.com/strangerstudios/paid-memberships-pro/commit/6e479b81606b5cebc9cf7d92d969337fc4a5030d#diff-20a7c748561106d979dac7b5825b61be

That was a while ago, we might have done commits later, but that should be the ... gist ... of it.

**Comment by andrewlimaza** [comment]
PR - https://github.com/strangerstudios/pmpro-payfast/pull/36
