### ISSUE TITLE
Better prefixes for constants and functions.

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/pmpro-payfast#41]
## Generic function (and/or define) names 

All plugins must have unique function names, namespaces, defines, and classnames. This prevents your plugin from conflicting with other plugins or themes. We need you to update your plugin to use more unique and distinct names.

A good way to do this is with a prefix. For example, if your plugin is called "Easy Custom Post Types" then you could use names like these:

function ecpt_save_post()
define( ‘ECPT_LICENSE’, true );
class ECPT_Admin{}
namespace EasyCustomPostTypes;

Don't try to use two letter slugs anymore. We have over 60 THOUSAND plugins on WordPress.org alone, you’re going to run into conflicts. 

Similarly, don't use __ (double underscores), wp_ , or _ (single underscore) as a prefix. Those are reserved for WordPress itself. You can use them inside your classes, but not as stand-alone function.

Remember: Good names are unique and distinct. This will help you and the next person in debugging, as well as prevent conflicts.

Some examples from your plugin:

define( 'PF_SOFTWARE_NAME', 'Paid Memberships Pro' );
define( 'PF_SOFTWARE_VER', PMPRO_VERSION );

**Comment by andrewlimaza** [comment]
This has been resolved in latest commit.
