### ISSUE TITLE
Fatal Error when updating the Billing Page.

### ISSUE THREAD

**Issue by AnsieLima** [strangerstudios/pmpro-payfast#49]
A user using PayFast is getting an Error when they attempt to update the billing page:

Fatal error: Uncaught Error: Call to undefined method PMProGateway_PayFast::update()
in /home/_________/wp-content/plugins/paid-memberships-pro/classes/class.memberorder.php on line 899

Call stack:

MemberOrder::updateBilling()
wp-content/plugins/paid-memberships-pro/preheaders/billing.php:214
require_once()
wp-content/plugins/paid-memberships-pro/includes/init.php:75
pmpro_wp()
wp-includes/class-wp-hook.php:287
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:311
WP_Hook::do_action()
wp-includes/plugin.php:544
do_action_ref_array()
wp-includes/class-wp.php:752
WP::main()
wp-includes/functions.php:1274
wp()
wp-blog-header.php:16
require()
index.php:17
--

**Comment by jamiehlake** [comment]
Glad to see I'm not the only one :) hopefully the fix comes soon.

**Comment by andrewlimaza** [comment]
@jamiehlake we are busy fixing this. You may disable the billing page/remove it from your menus site etc. It's not needed for Offsite gateways like PayFast.

The solution I've come up with is to just redirect the update button to PayFast URL and show a notice about it. As mentioned this page isn't needed.

<img width="802" alt="payfast-billing-page-update" src="https://user-images.githubusercontent.com/12629136/86230655-a6b8c380-bb91-11ea-9934-d111e3a007ec.png">

We will continue to work through Paid Memberships Pro core updates to make this easier for plugin developers to integrate with. This update should come out in the next week or two. You can keep an eye on the 'dev' branch for a pre-release. If you need help applying this pre-patch to your site, please feel free to open a ticket on www.paidmembershipspro.com

Thank you for understanding.

**Comment by andrewlimaza** [comment]
This has just been merged into the dev branch (https://github.com/strangerstudios/pmpro-payfast/pull/50). This should release in the near future, we just are going to run a couple of more tests before releasing it publicly.

**Comment by jamiehlake** [comment]
Thank you very much, really appreciate the response.
