### ISSUE TITLE
Payfast logo still shows for FREE members

### ISSUE THREAD

**Issue by bluesteamhost** [strangerstudios/pmpro-payfast#58]
When the gateway is set to FREE by entering a free for life discount code that makes the membership subscription free, the PayFast logo is still shown. It should be hidden/removed from view.

![image](https://user-images.githubusercontent.com/44110924/89553652-16177800-d80e-11ea-94e1-9173aee40d8f.png)

**Comment by andrewlimaza** [comment]
This issue has been resolved in the latest version. If you are still experiencing issues, please feel free to open a new issue on Github.
