### ISSUE TITLE
Payfast recurring payment 

### ISSUE THREAD

**Issue by Makeneta** [strangerstudios/pmpro-payfast#62]
I'm using paid membership pro to make payments but my problem is when i do ones off payment it's working. It gives me problem when I do recaring payment is say : signature mismatch occurred what can be the problem.

I dont know much with payfast I'm new please help me

**Comment by andrewlimaza** [comment]
Hi @Makeneta 

Thank you for reaching out, please feel free to open a support ticket here - https://en-za.wordpress.org/plugins/pmpro-payfast/

To briefly touch on your issue, this sounds like you are missing a passphrase (required for recurring payments) or there may be a trailing space/missing letter from your merchant details when pasting them into Paid Memberships Pro payment settings. I'll continue to assist you on our .org forums.

We use Github for bug tracking and not support queries. Thank you for understanding.
