### ISSUE TITLE
PHP Notice when creating or editing a level

### ISSUE THREAD

**Issue by JarrydLong** [strangerstudios/pmpro-payfast#67]
Notice: Trying to get property 'cycle_period' of non-object in /srv/users/jarrydlong-dev/apps/jarrydlong-dev/public/wp-content/plugins/pmpro-payfast/pmpro-payfast.php on line 136

Notice: Trying to get property 'cycle_period' of non-object in /srv/users/jarrydlong-dev/apps/jarrydlong-dev/public/wp-content/plugins/pmpro-payfast/pmpro-payfast.php on line 136

WP - 5.5.1
PMPro - 2.4.4
PMPro Payfast - 0.9

**Comment by andrewlimaza** [comment]
This has been fixed.
