### ISSUE TITLE
Add setting to specify a rate to from USD to RAND 

### ISSUE THREAD

**Issue by chavu** [strangerstudios/pmpro-payfast#71]
I would like to be able to multiple the price amount before it is sent to Payfast gateway by a rate that should be configurable.  This is useful to enable PaidmembershipPro user to pay either via Payfast which supports ZAR and not USD or pay by Paypal which support USD and not ZAR.

**Comment by andrewlimaza** [comment]
Hi @chavu 

You may see this repo I built in my spare-time but did not release publicly as a starting point. **This is most likely outdated and will need work. Please feel free to fork it and adjust it accordingly**

https://github.com/andrewlimaza/pmpro-convert-to-usd

**Comment by chavu** [comment]
@andrewlimaza:
Thanks. I had a quick look at your repo and it looks like a good generic solution. 
Yesterday I had done my own  quick hack in 'pmpro-payfast' plugin as a prototype which I could then do a PULL request if viable. My approach is to change from any default currency to ZAR. I made the following changes inside the 'class.pmprogateway_payfast.php' file :
1. Added an 'payfast_exchange_rate' field to payment settings page. (instead of this I could use your 'pcc_convert_amount_usd'  function which pulls the rate from an API which is more elegant)
2.  Incorporate the rate (conversion) at the point where the taxes are calculated as below:

```
		// taxes on initial payment
		$initial_payment     = round( (float) $order->InitialPayment *  floatval($rate), 2); //LC -multiplying the Base currency by exchange rate to get the ZAR amount
		$initial_payment_tax = $order->getTaxForPrice( $initial_payment );
		$initial_payment     = round( (float) $initial_payment + (float) $initial_payment_tax, 2 );

	    // taxes on the amount
		$amount          = $order->PaymentAmount *  floatval($rate); //LC -multiplying the Base currency by exchange rate to get the ZAR amount
		$amount          = round( (float) $amount, 2);
		$order->subtotal = $amount;
		$amount_tax      = $order->getTaxForPrice( $amount );
		$amount          = round( (float) $amount + (float) $amount_tax, 2 );
```

I have discovered  a problem with my approach already. The invoices are showing the default currency (USD) and yet figures are ZAR values. I'm yet to figure out how to resolve that.

**Comment by andrewlimaza** [comment]
Thanks for the feedback @chavu it seems you are on the right track so far, We are not going support this as it will cause a lot of 'tech debt' to our product as well as support. If you're selling to US/International customers I recommend using a different gateway like PayPal Express or reach out to PayFast to support USD currency conversion on their end.

If you need further assistance with this, please reach out to a local WordPress developer.

Thanks for understanding.
