### ISSUE TITLE
Not redirecting to payfast on check out for new account

### ISSUE THREAD

**Issue by Robmobius** [strangerstudios/pmpro-payfast#72]
Payfast for PMPRO installed and single membership level created. 

Select the membership from the membership level page and proceed to check out. 

Complete the Account information form and click "Submit and check out"

Expected action - redirected to the payfast site for payment

Actual action - loads page 1 of one of my courses. (? why this page, in particular, I have no idea)

On the back end, there is no new member created but a new user with the role subscriber is created. 

If, while logged as the new subscriber, ie after the steps above, I try and buy the membership level then it works as expected. 

It seems as though the payfast check out redirect option only works for logged in users. I have tested in sandbox and production modes with the same result.

**Comment by andrewlimaza** [comment]
@Robmobius This channel is used for bug reports/issues relating directly to the code. We don't monitor these issues as frequent as our dedicated support channels, and the best place to reach out for support is either https://wordpress.org/plugins/pmpro-payfast/ or https://www.paidmembershipspro.com

I haven't been able to replicate this issue. If you're still having issues with this, please can you open a support ticket on one of the above and we'll continue to assist you.

Thanks for understanding.
