### ISSUE TITLE
Cancellation Issues

### ISSUE THREAD

**Issue by ntweed** [strangerstudios/pmpro-payfast#73]
When someone cancels on the website, it is cancelling fine, however, it is is not cancelling with PayFast. 

This is the error email we get:

**There was an error canceling the subscription for user with ID=146. You will want to check your payment gateway to see if their subscription is still active.

Error: Length Required**

**Comment by andrewlimaza** [comment]
I believe this has been fixed with the latest version, please do not hesitate to reach out to our support on www.paidmembershipspro.com if you have any further questions.
