### ISSUE TITLE
pmpro-payfast plugin -Not Updated

### ISSUE THREAD

**Issue by KebiMalo** [strangerstudios/pmpro-payfast#77]
Please note that the plugin has not been updated for 5months. Will there be any updates soon?

**Comment by andrewlimaza** [comment]
Hi @KebiMalo 

Thanks for reaching out. We do update as need be, please note that Paid Memberships Pro - PayFast works with the latest version of WordPress (We'll update the tested up to value shortly).

If you have any support questions, please open a support thread here - https://wordpress.org/plugins/pmpro-payfast/
