### ISSUE TITLE
Payfast signature error from PMPRO

### ISSUE THREAD

**Issue by cobusvl** [strangerstudios/pmpro-payfast#91]
Good Day
If I use the uses a normal payfast plugin from within woocommerce, the live setting merchant ID and merchant Key works. Have tested this and it works fine.
When using this plugin as an add on with Paid Membership Pro, i did the same thing with same merchant ID and merchant Key from the both live testing and sandbox.payfast.co.za, it keeps giving signature mismatch.
I have followed the instructions and I am at a loss with this add on.
I have also contacted Payfast support but they are of the opinion that it is a PMPRo Plugin issue.
Any help would be appreciated.

**Comment by cobusvl** [comment]
Hi, I took the issue to Payfast as I needed help and it seems no one is answering here, and the following is a message I received from Payfast. I do understand that Pmpro wants to sell support but thus is a standard plugin "one time" issue and I hope to get help here.
From Payfast: 
"I have received feedback from our plugin developers and they have advised the below:

The pmpro-payfast plugin uses an outdated signature match functionality and is not maintained by Payfast. The plugin is available at https://www.paidmembershipspro.com/add-ons/payfast-payment-gateway/ and the repo is available at https://github.com/strangerstudios/pmpro-payfast.

You would be required to contact PMPRO presale team at https://www.paidmembershipspro.com/support/ or using https://github.com/strangerstudios/pmpro-payfast/issues.

**Comment by andrewlimaza** [comment]
Hi @cobusvl 

Sorry for the delayed reply, we do not offer support through GitHub and don't actively track these repositories for urgent support requests like this. I apologize about this.

It would be best to reach out to [our support channel](https://www.paidmembershipspro.com/support) as you mentioned in your response or on the [WordPress.org ](https://wordpress.org/support/plugin/pmpro-payfast/)download page.

However, I haven't been able to replicate this in sandbox. **Please note that the passphrase is required** and not optional for recurring subscriptions. I also recommend to set this regardless of your billing settings.

I'm not sure if you have moved on already, but I thought to reply here. I hope this helps clear up your questions.
