### ISSUE TITLE
Level restricted user fields does not save on checkout.

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-payfast#99]
When checking out for a paid level that has user fields restricted to appear for that level, the user field data is not saved. When checking out for a free level that has user fields restricted for that level the fields are saved successfully. If PayFast is set as the main gateway and checkout is processed for a paid level using the Check gateway (via Pay By Check Add On) the restricted level fields are not saved.

In both above paid-level scenarios, the fields that were not restricted to a specific level were saved successfully.
Testing was completed using both unrestricted and level-restricted user fields created via settings as well as user fields created via code.

**To replicate:**
1. Install, activate, and configure the PayFast Add On.
2. Create a free level and a paid level.
3. Create user fields and restrict them to the above levels.
4. Create user fields that are not restricted to specific levels.
5. Check out for the free level and verify all user fields were saved.
6. Check out for the paid level and verify that unrestricted fields were saved and level-restricted user fields were not saved.

**Screenshots**

![2024-08-23_15-04-52](https://github.com/user-attachments/assets/cb78bc66-f99f-4de3-9787-651fc6dc4691)

**Expected behavior**
Level-restricted user field data to save on checkout for paid levels.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
Paid Memberships Pro 3.1.3<br />
PayFast Add On 1.5.2
</details>

**Comment by ipokkel** [comment]
Moderators Only:
Ticket: #589870

**Comment by andrewlimaza** [comment]
This has been resolved! :)
